# Generated by Django 4.1.5 on 2023-01-14 22:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="display_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="transfertransaction",
            name="fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.0"), max_digits=20
            ),
        ),
    ]
