# Generated by Django 4.1.5 on 2023-01-14 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_account_display_number_alter_transfertransaction_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="housechorerewardrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
